### ISSUE TITLE
Question: Pourquoi ?

### ISSUE THREAD

**Issue by Jorand** [Yenaman/chiasse#1]
En cherchant tusmo.xyz je tombe sur ce dépôt et je suis curieux, pourquoi ?

have fun :)

**Comment by Yenaman** [comment]
C’est un site entre potes où on met plusieurs liens de jeux auxquels on
joue fréquemment, TusMo en fait partie :)

**Comment by Jorand** [comment]
C'est ce que je me suis dit 😆 Merci pour ta réponse je close cette issue !

Très beau nom de domaine btw!
